// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADdj7HBidfDxJ1LnX5_oO9-toIHmGwGNk',
    appId: '1:1066473564035:android:758635a1bfac63bbfef8b6',
    messagingSenderId: '1066473564035',
    projectId: 'dima-2c0a8',
    storageBucket: 'dima-2c0a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo0o5X2mHikYiLzIZjPTw42GVqLi3NyYI',
    appId: '1:1066473564035:ios:842f07ed702fa81bfef8b6',
    messagingSenderId: '1066473564035',
    projectId: 'dima-2c0a8',
    storageBucket: 'dima-2c0a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );


}
